In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
dataframe=pd.read_csv(r'C:\Users\toshiba\Desktop\PYTHON\dataset.csv')
dataframe

,Address,F.S,P.C.S,M.E,F.E,M.J,F.J,HTS trave ltime,DST,Failures,...,Internet access at home,In a relationship,Going out with friends,Current health status,No of absences from class in a month,Grade at Class 8,9th Class first term Grade,9th Class Second term Grade,Quality of family relationships,Gender
0,Urban,Greater than 3,Living together,Higher Education,Higher Education,Yes,Yes,"<15 min,","2 to 5 hours,",No,...,Yes,No,No,Good,1,A+,A+,A+,Very Good,Female
1,Urban,Greater than 3,Apart,Secondary Education,Higher Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,No,Yes,Very Good,1,B,B+,B,Very Good,Female
2,Rural,Greater than 3,Living together,Elementary Education,Secondary Education,No,Yes,"15 to 30 min,","<2 hours,",No,...,Yes,No,No,Good,1,B,B,B+,Very Good,Female
3,Rural,Greater than 3,Living together,Secondary Education,Secondary Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,No,Yes,Good,1,A+,A+,A+,Good,Female
4,Urban,Greater than 3,Living together,Secondary Education,Elementary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,No,Very Good,1,A+,B,B+,Very Good,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,Rural,Less or equal to 3,Apart,Elementary Education,NaN,Yes,No,"15 to 30 min,","<2 hours,",Yes,...,No,Yes,No,Very Good,2,A+,A,A,Good,Male
1199,Urban,Less or equal to 3,Living together,Elementary Education,Secondary Education,Yes,Yes,"15 to 30 min,","<2 hours,",Yes,...,Yes,Yes,Yes,Good,1,A,A,A,Good,Female
1200,Urban,Less or equal to 3,Living together,Secondary Education,Secondary Education,No,No,"30 min. to 1 hour,","2 to 5 hours,",Yes,...,No,Yes,Yes,Not Good,3,B,B,A,Not Good,Male
1201,Rural,Greater than 3,Apart,NaN,Elementary Education,Yes,No,"<15 min,","2 to 5 hours,",Yes,...,No,Yes,Yes,Good,2,B+,A,B,Good,Male
1202,Urban,Greater than 3,Living together,Secondary Education,Secondary Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,Yes,Yes,Good,3,A+,A+,A+,Very Good,Female

In [6]:
dataframe.head(15)

,Address,F.S,P.C.S,M.E,F.E,M.J,F.J,HTS trave ltime,DST,Failures,...,Internet access at home,In a relationship,Going out with friends,Current health status,No of absences from class in a month,Grade at Class 8,9th Class first term Grade,9th Class Second term Grade,Quality of family relationships,Gender
0,Urban,Greater than 3,Living together,Higher Education,Higher Education,Yes,Yes,"<15 min,","2 to 5 hours,",No,...,Yes,No,No,Good,1,A+,A+,A+,Very Good,Female
1,Urban,Greater than 3,Apart,Secondary Education,Higher Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,No,Yes,Very Good,1,B,B+,B,Very Good,Female
2,Rural,Greater than 3,Living together,Elementary Education,Secondary Education,No,Yes,"15 to 30 min,","<2 hours,",No,...,Yes,No,No,Good,1,B,B,B+,Very Good,Female
3,Rural,Greater than 3,Living together,Secondary Education,Secondary Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,No,Yes,Good,1,A+,A+,A+,Good,Female
4,Urban,Greater than 3,Living together,Secondary Education,Elementary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,No,Very Good,1,A+,B,B+,Very Good,Female
5,Urban,Greater than 3,Living together,Secondary Education,Higher Education,No,Yes,"15 to 30 min,","5 to 10 hours,",No,...,Yes,No,No,Good,3,A+,A,A+,Very Good,Female
6,Urban,Greater than 3,Living together,Secondary Education,Secondary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,Yes,Good,2,B,B,B,Good,Male
7,Rural,Less or equal to 3,Apart,Secondary Education,Secondary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,No,Yes,No,Very Good,2,A+,B,A,Very Good,Female
8,Urban,Greater than 3,Living together,Secondary Education,Higher Education,No,Yes,"<15 min,","5 to 10 hours,",No,...,No,No,No,Good,2,A+,B+,C,Good,Female
9,Urban,Greater than 3,Apart,Secondary Education,Secondary Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,Yes,Yes,Good,3,A,A,B+,Not Good,Male
10,Urban,Greater than 3,Living together,Secondary Education,Higher Education,No,Yes,"<15 min,","2 to 5 hours,",No,...,Yes,No,Yes,Very Good,1,A+,A,A,Very Good,Male
11,Urban,Less or equal to 3,Living together,Secondary Education,Secondary Education,No,No,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,No,Very Good,3,B+,B,A,Good,Female
12,Urban,Less or equal to 3,Apart,Secondary Education,Higher Education,No,Yes,>1 hour,"2 to 5 hours,",No,...,No,No,No,Good,2,A+,D,A,Good,Female
13,Urban,Greater than 3,Living together,Higher Education,Higher Education,No,Yes,"<15 min,","2 to 5 hours,",No,...,Yes,No,No,Very Good,1,A+,B,A+,Very Good,Female
14,Urban,Greater than 3,Living together,Higher Education,Secondary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,No,Good,3,A,B,A,Good,Female

In [7]:
dataframe.tail(10)

,Address,F.S,P.C.S,M.E,F.E,M.J,F.J,HTS trave ltime,DST,Failures,...,Internet access at home,In a relationship,Going out with friends,Current health status,No of absences from class in a month,Grade at Class 8,9th Class first term Grade,9th Class Second term Grade,Quality of family relationships,Gender
1193,Urban,Greater than 3,Living together,Secondary Education,Higher Education,No,No,"15 to 30 min,","5 to 10 hours,",No,...,Yes,No,Yes,Good,2,A,A,A,Good,Male
1194,Urban,Greater than 3,Apart,Elementary Education,Elementary Education,Yes,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,No,No,No,Good,3,A,A,A,Very Good,Male
1195,Rural,Less or equal to 3,Apart,Elementary Education,Elementary Education,Yes,No,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,No,No,Good,2,A,A,A+,Very Good,Female
1196,Urban,Greater than 3,Apart,Secondary Education,Elementary Education,No,No,"15 to 30 min,","2 to 5 hours,",Yes,...,Yes,Yes,No,Not Good,2,B,C,B+,Good,Female
1197,Urban,Less or equal to 3,Living together,Elementary Education,Elementary Education,Yes,Yes,"15 to 30 min,","2 to 5 hours,",No,...,No,No,No,Not Good,3,B,B+,A,Very Good,Male
1198,Rural,Less or equal to 3,Apart,Elementary Education,NaN,Yes,No,"15 to 30 min,","<2 hours,",Yes,...,No,Yes,No,Very Good,2,A+,A,A,Good,Male
1199,Urban,Less or equal to 3,Living together,Elementary Education,Secondary Education,Yes,Yes,"15 to 30 min,","<2 hours,",Yes,...,Yes,Yes,Yes,Good,1,A,A,A,Good,Female
1200,Urban,Less or equal to 3,Living together,Secondary Education,Secondary Education,No,No,"30 min. to 1 hour,","2 to 5 hours,",Yes,...,No,Yes,Yes,Not Good,3,B,B,A,Not Good,Male
1201,Rural,Greater than 3,Apart,NaN,Elementary Education,Yes,No,"<15 min,","2 to 5 hours,",Yes,...,No,Yes,Yes,Good,2,B+,A,B,Good,Male
1202,Urban,Greater than 3,Living together,Secondary Education,Secondary Education,No,Yes,"30 min. to 1 hour,","2 to 5 hours,",No,...,Yes,Yes,Yes,Good,3,A+,A+,A+,Very Good,Female

In [8]:
dataframe.dtypes

Address                                 object
F.S                                     object
P.C.S                                   object
M.E                                     object
F.E                                     object
M.J                                     object
F.J                                     object
HTS trave ltime                         object
DST                                     object
Failures                                object
E.C                                     object
Attended nursery school                 object
Wants to take higher education          object
Internet access at home                 object
In a relationship                       object
Going out with friends                  object
Current health status                   object
No of absences from class in a month    object
Grade at Class 8                        object
9th Class first term Grade              object
9th Class Second term Grade             object
Quality of family relationships         object
Gender                                  object
dtype: object

In [9]:
dataframe.describe

<bound method NDFrame.describe of      Address                 F.S            P.C.S                   M.E  \
0      Urban      Greater than 3  Living together      Higher Education
1      Urban      Greater than 3            Apart   Secondary Education
2      Rural      Greater than 3  Living together  Elementary Education
3      Rural      Greater than 3  Living together   Secondary Education
4      Urban      Greater than 3  Living together   Secondary Education
...      ...                 ...              ...                   ...
1198   Rural  Less or equal to 3            Apart  Elementary Education
1199   Urban  Less or equal to 3  Living together  Elementary Education
1200   Urban  Less or equal to 3  Living together   Secondary Education
1201   Rural      Greater than 3            Apart                   NaN
1202   Urban      Greater than 3  Living together   Secondary Education

                       F.E  M.J  F.J     HTS trave ltime            DST  \
0         Higher Education  Yes  Yes            <15 min,  2 to 5 hours,
1         Higher Education   No  Yes  30 min. to 1 hour,  2 to 5 hours,
2      Secondary Education   No  Yes       15 to 30 min,      <2 hours,
3      Secondary Education   No  Yes  30 min. to 1 hour,  2 to 5 hours,
4     Elementary Education   No  Yes       15 to 30 min,  2 to 5 hours,
...                    ...  ...  ...                 ...            ...
1198                   NaN  Yes   No       15 to 30 min,      <2 hours,
1199   Secondary Education  Yes  Yes       15 to 30 min,      <2 hours,
1200   Secondary Education   No   No  30 min. to 1 hour,  2 to 5 hours,
1201  Elementary Education  Yes   No            <15 min,  2 to 5 hours,
1202   Secondary Education   No  Yes  30 min. to 1 hour,  2 to 5 hours,

     Failures  ... Internet access at home  In a relationship   \
0          No  ...                      Yes                 No
1          No  ...                      Yes                 No
2          No  ...                      Yes                 No
3          No  ...                      Yes                 No
4          No  ...                      Yes                 No
...       ...  ...                      ...                ...
1198      Yes  ...                       No                Yes
1199      Yes  ...                      Yes                Yes
1200      Yes  ...                       No                Yes
1201      Yes  ...                       No                Yes
1202       No  ...                      Yes                Yes

     Going out with friends Current health status   \
0                        No                   Good
1                       Yes              Very Good
2                        No                   Good
3                       Yes                   Good
4                        No              Very Good
...                     ...                    ...
1198                     No              Very Good
1199                    Yes                   Good
1200                    Yes               Not Good
1201                    Yes                   Good
1202                    Yes                   Good

     No of absences from class in a month Grade at Class 8  \
0                                       1               A+
1                                       1                B
2                                       1                B
3                                       1               A+
4                                       1               A+
...                                   ...              ...
1198                                    2               A+
1199                                    1                A
1200                                    3                B
1201                                    2               B+
1202                                    3               A+

     9th Class first term Grade 9th Class Second term Grade  \
0                            A+                          A+
1                            B+                           B
2                             B                          B+
3                            A+                          A+
4                             B                          B+
...                         ...                         ...
1198                          A                           A
1199                          A                           A
1200                          B                           A
1201                          A                           B
1202                         A+                          A+

     Quality of family relationships  Gender
0                          Very Good  Female
1                          Very Good  Female
2                          Very Good  Female
3                               Good  Female
4                          Very Good  Female
...                              ...     ...
1198                            Good    Male
1199                            Good  Female
1200                        Not Good    Male
1201                            Good    Male
1202                       Very Good  Female

[1203 rows x 23 columns]>

In [10]:
dataframe.describe(include="all")

,Address,F.S,P.C.S,M.E,F.E,M.J,F.J,HTS trave ltime,DST,Failures,...,Internet access at home,In a relationship,Going out with friends,Current health status,No of absences from class in a month,Grade at Class 8,9th Class first term Grade,9th Class Second term Grade,Quality of family relationships,Gender
count,1203,1203,1203,1043,1074,1203,1203,1203,1203,1203,...,1203,1203,1203,1203,1203,1203,1203,1203,1203,1203
unique,2,2,2,3,3,2,2,4,4,2,...,2,2,2,3,4,6,7,7,3,2
top,Urban,Greater than 3,Living together,Secondary Education,Elementary Education,No,Yes,"15 to 30 min,","2 to 5 hours,",No,...,Yes,No,No,Good,2,A,A,A,Good,Female
freq,667,707,711,458,436,724,773,532,565,805,...,694,754,641,641,449,361,361,352,574,636

In [13]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1203 entries, 0 to 1202
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Address                               1203 non-null   object
 1   F.S                                   1203 non-null   object
 2   P.C.S                                 1203 non-null   object
 3   M.E                                   1043 non-null   object
 4   F.E                                   1074 non-null   object
 5   M.J                                   1203 non-null   object
 6   F.J                                   1203 non-null   object
 7   HTS trave ltime                       1203 non-null   object
 8   DST                                   1203 non-null   object
 9   Failures                              1203 non-null   object
 10  E.C                                   1203 non-null   object
 11  Attended nursery school               1203 non-null   object
 12  Wants to take higher education        1203 non-null   object
 13  Internet access at home               1203 non-null   object
 14  In a relationship                     1203 non-null   object
 15  Going out with friends                1203 non-null   object
 16  Current health status                 1203 non-null   object
 17  No of absences from class in a month  1203 non-null   object
 18  Grade at Class 8                      1203 non-null   object
 19  9th Class first term Grade            1203 non-null   object
 20  9th Class Second term Grade           1203 non-null   object
 21  Quality of family relationships       1203 non-null   object
 22  Gender                                1203 non-null   object
dtypes: object(23)
memory usage: 216.3+ KB

In [14]:
dataframe.to_csv('saveddataset.csv')